### ISSUE TITLE
Add a test with aarch64 rpm package

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#30]
Add a test to verify aarch64 rpm package works

**Comment by 0crat** [comment]
The job [#30](https://github.com/artipie/rpm-adapter/issues/30) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1f17fca8-13ed-4269-9334-24f2e376a0f5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#32](https://github.com/artipie/rpm-adapter/issues/32) is still not solved.

**Comment by g4s8** [comment]
Solved in #31

**Comment by 0crat** [comment]
Job was finished in 20 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#40](https://github.com/artipie/rpm-adapter/issues/40) is still not solved; solved: [#32](https://github.com/artipie/rpm-adapter/issues/32).

**Comment by 0pdd** [comment]
@g4s8 all 2 puzzles are solved here: [#32](https://github.com/artipie/rpm-adapter/issues/32), [#40](https://github.com/artipie/rpm-adapter/issues/40).
