### ISSUE TITLE
Subdirectories in rpm repository 

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#376]
Rpms in the rpm repository can be organized in subdirectories, tag `location` in the `primary.xml` should specify rpm file location relatively to the rpm repository, for example for file structure:
```
../
repodata/
subdir/
    rpm_in_subdir.rpm
rpm_not_in_subdir.rpm
```
`primary.xml` should contain `location` tags
```xml
<package type="rpm">
  <name>rpm_in_subdir</name>
  ...
  <location href="subdir/rpm_in_subdir.rpm"/>
  ...
</package>
<package type="rpm">
  <name>rpm_not_in_subdir</name>
  ...
  <location href="rpm_not_in_subdir.rpm"/>
  ...
</package>
```

**Comment by olenagerasimova** [comment]
@rultor release, tag=`1.3.1`

**Comment by olenagerasimova** [comment]
@olegmoz I've released a new version and it is already available in maven central. Could you please inform our colleagues to try new release?

**Comment by olenagerasimova** [comment]
@rultor release, tag=`1.3.2`

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#391](https://github.com/artipie/rpm-adapter/issues/391) is still not solved.

**Comment by 0pdd** [comment]
@olenagerasimova the only puzzle [#391](https://github.com/artipie/rpm-adapter/issues/391) is solved here.
