### ISSUE TITLE
Type of the primary `file` entity

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#501]
`File` entity of the primary xml can have attribute `type` with `dir` or `ghost` values. Now, we add only `dir` but not precisely as it is done in `createrepo`. Thus, we need:
1) to analyze the [condition](https://github.com/rpm-software-management/createrepo_c/blob/b49b8b2586c07d3e84009beba677162b86539f9d/src/parsehdr.c#L278) in `createrepo` by which `type=dir` is added  
2) to analyze the [condition](https://github.com/rpm-software-management/createrepo_c/blob/b49b8b2586c07d3e84009beba677162b86539f9d/src/parsehdr.c#L281)  in `createrepo` by which `type=ghost` is added

and implement adding attribute `type` with `dir` or `ghost` values exactly as it is done in `createrepo`. 

Check the links on "condition" words, they lead to `createrepo` code; in rpm-adapter check `XmlEvent.Files`, `HeaderTags#baseNames` and `HeaderTags#dirNames`.

**Comment by olenagerasimova** [comment]
@g4s8 do not you mind assigning this issue to @baudoliver7 ? C knowledge would be definitely helpful here

**Comment by baudoliver7** [comment]
@olenagerasimova There is an issue with @0pdd. Expected puzzle haven't been generated.

**Comment by baudoliver7** [comment]
@olenagerasimova It has been resolved now. At the next commit on `master`, puzzle will be generated.

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#512](https://github.com/artipie/rpm-adapter/issues/512) is still not solved.

**Comment by 0pdd** [comment]
@olenagerasimova the only puzzle [#512](https://github.com/artipie/rpm-adapter/issues/512) is solved here.
